baseURL = "https://dioclecio.com/"
languageCode = "pt-br"
defaultContentLanguage = "pt-br"
title = "Dioclecio"
theme = "ananke"

# SectionPagesMenu = "main"

Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "G-753L8QXCLP"
enableRobotsTXT = true

# menu = 'main'

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = "/img/2022/logo.png"
  description = "Algumas reflexões e projetos para expor"
  # facebook = ""
  twitter = "https://twitter.com/DioclecioCom"
  # instagram = ""
  # youtube = ""
  github = "https://github.com/dioclecio"
  # gitlab = ""
  # linkedin = ""
  # mastodon = ""
  # slack = ""
  # stackoverflow = ""
  # rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/img/2022/peter-lawrence-hdhNFQQje0s-unsplash.jpg"
  recent_posts_number = 3

[menu]
  [[menu.main]]
      name = "Principal"
      pre = "<i class='fa fa-heart'></i>"
      weight = -110
      identifier = "home"
      url = "/"
  [[menu.main]]
      name = "Blog"
      pre = "<i class='fa fa-road'></i>"
      weight = -100
      url = "/blog/"
  [[menu.main]]
      name = "Projetos"
      pre = "<i class='fa fa-road'></i>"
      weight = -90
      url = "/projetos/"

  [[menu.main]]
      name = "Contato"
      pre = "<i class='fa fa-road'></i>"
      weight = -1
      url = "/contato/"
